[package]
name = "serde_docs"
version = "0.1.0"
authors = ["David Tolnay <dtolnay@gmail.com>"]

[dependencies]
erased-serde = "*"
serde = "*"
serde-transcode = "*"
serde_derive = "*"
serde_json = "*"
serde_test = "*"
serde_xml = "*"
syntex = "*"
