[package]
name = "serde_docs"
version = "0.1.0"
authors = ["David Tolnay <dtolnay@gmail.com>"]

[dependencies]
aster = "*"
quasi = "*"
serde = "*"
serde_json = "*"
serde_macros = "*"
serde_test = "*"
syntex = "*"
