[package]
name = "serde_docs"
version = "0.1.0"
authors = ["David Tolnay <dtolnay@gmail.com>"]

[dependencies]
aster = "0.22.1"
quasi = "0.16.0"
serde = "0.8.1"
serde_json = "0.8.1"
serde_test = "0.8.1"
