[package]
name = "serde_docs"
version = "0.0.0"
authors = ["David Tolnay <dtolnay@gmail.com>"]
publish = false

[dependencies]
serde = "*"
serde-transcode = "*"
serde_bytes = "*"
serde_derive = "*"
serde_json = "*"
serde_test = "*"
serde_yaml = "*"
